extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
plugins:
  - stylelint-no-unsupported-browser-features
  - stylelint-scss
rules:
  import-notation: string
  no-descending-specificity: ~
