extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
plugins:
  - stylelint-no-unsupported-browser-features
rules:
  import-notation: string
  no-descending-specificity: ~
  scss/at-extend-no-missing-placeholder: null
